### ISSUE TITLE
some errors on readme file

### ISSUE THREAD

**Issue by ikerib** [kreta-io/kreta#65]
Where it says
   git clone --recursive https://github.com/kreta/kreta.git kreta

should be:
   git clone --recursive https://github.com/kreta-io/kreta.git kreta

and small typo error on: 
   $ cd /vagrant
   $ vagrant up
   $ vagran ssh  <=== 't' is missing ;)

Lan bikaina txabales! ;)

**Comment by gorkalaucirica** [comment]
Eskerrik asko Iker, we'll fix it as soon as posible

**Comment by gorkalaucirica** [comment]
Fixed!
